name: rpi_gpio
version: 0.2.0
author: Dan Rubel <danrubel@google.com>
description: rpi_gpio is a Dart library for accessing the Raspberry Pi GPIO pins.
homepage: https://github.com/danrubel/rpi_gpio.dart
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  path: '>=1.0.0 <2.0.0'
dev_dependencies:
  unittest: '>=0.11.4 <0.12.0'
